# Generated by Django 3.1.3 on 2021-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parasite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_info', models.CharField(max_length=600)),
                ('host', models.CharField(max_length=150)),
                ('disease', models.CharField(max_length=65)),
                ('geographic_distribution', models.CharField(max_length=400)),
                ('prophylaxis', models.CharField(max_length=2100)),
            ],
        ),
    ]
