# Generated by Django 3.1.3 on 2021-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasiteMaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parasite',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
